# Generated by Django 5.2 on 2025-05-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_studentabsence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAbsence',
        ),
    ]
